version: '3.8'

services:
  proxyrequest:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build: .
    container_name: proxyrequest

    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html

    restart: "no"
    extra_hosts:
      - "host.docker.internal:host-gateway"
